### PR TITLE
Add support for ignoring specific checks based on service and check name

### PR DESCRIPTION
**Pull request by ddelnano**
Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

__IMPORTANT:__ Please take note of the below checklist, especially the first three items.

# Summary

This PR adds support for skipping the result of specific checks. See #307 for more details.

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Whether or not your PR includes unit tests: **My PR includes tests and should have 100% coverage**
    - [x] Please make sure you have run the exact code contained in the PR locally, and it functions as desired. **I ran the code interactively even though my test coverage should be sufficient**

```
ddelnano@10-81-17-110-uswest2adevc:~$ BOTO_CONFIG=/etc/boto_cfg/resource-limit-monitor.cfg awslimitchecker --ta-refresh-wait --no-check-version -r us-west-2 -S EC2 -L 'EC2/Running On-Demand c5.9xlarge instances'=2000 -L 'EC2/Running On-Demand i3.large instances'=16 -L 'EC2/Running On-Demand i3.xlarge instances'=50 -L 'EC2/Running On-Demand m4.16xlarge instances'=16 -L 'EC2/Running On-Demand p3.8xlarge instances'=2 -L 'EC2/Max spot instance requests per region'=2000 -L 'EC2/VPC security groups per elastic network interface'=7 -L 'EC2/Running On-Demand x1e.8xlarge instances'=10
awslimitchecker 6.1.5 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
WARNING:awslimitchecker.trustedadvisor:Polling for TA check eW7HH0l7J9 refresh...
EC2/Max launch specifications per spot fleet  (limit 50) WARNING: sfr-98e516f0-62f8-47ad-ada6-444da23fe6c5=42

ddelnano@10-81-17-110-uswest2adevc:~$ BOTO_CONFIG=/etc/boto_cfg/resource-limit-monitor.cfg awslimitchecker --ta-refresh-wait --no-check-version -r us-west-2 -S EC2 -L 'EC2/Running On-Demand c5.9xlarge instances'=2000 -L 'EC2/Running On-Demand i3.large instances'=16 -L 'EC2/Running On-Demand i3.xlarge instances'=50 -L 'EC2/Running On-Demand m4.16xlarge instances'=16 -L 'EC2/Running On-Demand p3.8xlarge instances'=2 -L 'EC2/Max spot instance requests per region'=2000 -L 'EC2/VPC security groups per elastic network interface'=7 -L 'EC2/Running On-Demand x1e.8xlarge instances'=10 --skip-check 'EC2/Max launch specifications per spot fleet'
awslimitchecker 6.1.5 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
WARNING:awslimitchecker.trustedadvisor:Trusted Advisor check cannot be refreshed for another 253912 milliseconds; skipping refresh and getting check results now

ddelnano@10-81-17-110-uswest2adevc:~$ echo $?
0
```

 - [x] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

Here are what the docs look like when rebuilt.

Screen Shot 2019-04-04 at 4 27 49 PM
Screen Shot 2019-04-04 at 4 27 38 PM

### CODE REVIEW

**Comment by ddelnano** [comment]
@jantman have you gotten a chance to look at this? Is there anything else I need to do?

**Comment by jantman** [comment]
@ddelnano I'm sorry. I was on vacation last week and just got back today, and then will be at a regional conference for the next two days. Sorry for the delay, but I won't be able to get to this until later this week.

**Comment by ddelnano** [comment]
@jantman do you have time this week to check this PR out?

**Comment by jantman** [comment]
@ddelnano Apologies for this sitting so long.

Great work on this PR, thank you so much!!!

I'll try and get this released in the next day or two, time depending on what happens with #400.

**Comment by jantman** [comment]
@ddelnano Thank you so much for this! This has been released as [6.1.6](https://github.com/jantman/awslimitchecker/releases/tag/6.1.6) and is now available [on PyPI](https://pypi.org/project/awslimitchecker/)

**Pull request merged**
