### PR TITLE
Addressing TA checks issue (Issue #466)

### PR DESCRIPTION
**Pull request by tkim443**
Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

__IMPORTANT:__ Please take note of the below checklist, especially the first three items.

# Summary

I am making this pull request in an attempt to address the Trusted Advisor check issue in [Issue #466](https://github.com/jantman/awslimitchecker/issues/466). Instead of making one Trusted Advisor check in general for `performance/Service Limits`, I query for one specific service at a time, in the same loop that service quotas and API limits are updated. Therefore, I create a new function called `update_limits_per_service` in the hopes that `update_limits` can be phased out. 

While I have updated unit tests for the `tests/test_checker.py` file, I am having difficulty coming up with new ones for `tests/test_trustedadvisor.py`, so I would appreciate help on that. Meanwhile, since the old tests in `tests/test_trusted_advisor.py` still rely on the old `update_limits` function, I've left `update_limits` in for now.

My contribution is being made under the same license as the awslimitchecker project.

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Whether or not your PR includes unit tests:
    - [x] Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - [ ] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [ ] pep8 compliant with some exceptions (see pytest.ini)
    - [ ] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [ ] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [ ] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jacobisaliveandwell** [comment]
@jantman I'm going to try and take a look at this in the coming weeks, but would you mind please taking a look?

**Comment by jantman** [comment]
Thank you so much for your contribution, and please accept my apologies for not responding sooner. I've been quite busy lately and unable to dedicate any time to my open source projects. I'm going to make every effort to review this and get it merged sometime this week.

**Comment by jantman** [comment]
@tkim443 I've been looking into this, but unfortunately, I'm not sure that this implementation makes the most sense to me. Looking into how the ``service_limits`` category checks are organized in the ``DescribeTrustedAdvisorChecks`` API response, it looks like it's effectively just one big list of checks, with no clear way to tie them to services.

I think what makes the most sense is to describe all the checks and filter that returned list to only the ones for the ``service_limits`` category, and then for each of those, iterate all of our AwsLimit objects and update those that match. We'll likely have to make some changes to AwsLimit, since the checks now just report a "name" instead of a service name and limit name. While _most_ of those names are "<Service Name> <Limit Name>", they're just one string, and they're not _all_ in that format (i.e. the check with the name ``VPC``).

I'll do what I can to help this along, but as Trusted Advisor support is only needed by a small number of awslimitchecker users (those in China or GovCloud), it's unlikely that I'm going to implement this myself.

**Comment by jacobisaliveandwell** [comment]
> those in China or GovCloud

@jantman can you expand on this? I haven't touched this is a minute but if I recall correctly, it was throwing out warnings or errors related to TA, just during normal operation.

**Comment by jantman** [comment]
@jacobisaliveandwell correct. The warnings/errors don't affect operation beyond indicating that awslimitchecker isn't retrieving limit information from Trusted Advisor.

Trusted Advisor's service limit information has been _completely_ superseded by Service Quotas... but Service Quotas is (or was?) not available in China or GovCloud partitions/regions. Once Service Quotas are available _everywhere_, I plan on completely removing all Trusted Advisor integration. At this point, TA is really just there for China/Gov folks, even though it's currently not working...

**Comment by jantman** [comment]
Just coming back to this after quite a while.

Assuming it's complete and accurate, it looks like the [AWS China endpoints](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html) and [AWS GovCloud endpoints](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-endpoints.html) still lack Service Quotas. That's a shame. However, as far as I can tell, awslimitchecker Trusted Advisor support is still working in those partitions.

This has been superseded by #505.

**Pull request closed without merging**
