### PR TITLE
Replace "Max spot instance requests per region" limit with vCPU-based limits

### PR DESCRIPTION
**Pull request by TagadaPoe**
# Summary

BREAKING CHANGE

As mentioned in issue #502, the limit "Max spot instance requests per region" was removed from AWS and replaced by the following limits, based on the number of vCPU:
- All F Spot Instance Requests
- All G Spot Instance Requests
- All Inf Spot Instance Requests
- All P Spot Instance Requests
- All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests
- All X Spot Instance Requests

As a result, the usage reported by awslimitchecker is not relevant anymore.

In order to fix this, this commit replaces the call to the EC2 API describe_spot_instance_requests() with a call to the CloudWatch API, since the usage of Spot requests vCPUs is now available as a metric in CloudWatch.

In addition, the applied limits are now retrieved from the Service Quotas service.

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [ ] Whether or not your PR includes unit tests:
    - [x] Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - [ ] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@TagadaPoe I'm going to try to get to these PRs today, sorry for the delay. Could you please update your PR to [allow changes from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? This needs to be rebased on develop, and the others will need to be rebased as I merge them in. Thanks!

**Comment by jantman** [comment]
@TagadaPoe The code here looks good to me, but I'm a little confused by the default limits? In this PR I see the defaults as mostly 128 or 64, but at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html they seem to be much lower, i.e. 11 or 16 for many. Would you be so kind as to explain... I think I'm missing something here, or confused.

**Comment by TagadaPoe** [comment]
> @TagadaPoe I'm going to try to get to these PRs today, sorry for the delay. Could you please update your PR to [allow changes from maintainers](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? This needs to be rebased on develop, and the others will need to be rebased as I merge them in. Thanks!

I cannot see the "Allow edits from maintainers" link, is this because the PR is already in the "jantman/awslimitchecker repository" ?

**Comment by TagadaPoe** [comment]
> @TagadaPoe The code here looks good to me, but I'm a little confused by the default limits? In this PR I see the defaults as mostly 128 or 64, but at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-limits.html they seem to be much lower, i.e. 11 or 16 for many. Would you be so kind as to explain... I think I'm missing something here, or confused.

I fixed that, I am not sure where I took those values from...

**Comment by antonincms** [comment]
Hello @jantman, as said by @TagadaPoe we couldn't find the option to allow you to rebase our branch.
Maybe this is related to some parameters in our organization, or the fact the fork is owned by an organization (the doc you linked strangely mention `user-owned fork`, I don't know (I'm not the author of this PR either which won't help without recreating it).

Anyway, I rebased all three branches, don't hesitate to ping if you need rebasing or anything else.

**Comment by jantman** [comment]
Thank you so much for this, and apologies for the delay in merging it!

**Comment by jantman** [comment]
This has been released in [12.0.0](https://github.com/jantman/awslimitchecker/releases/tag/12.0.0), which is now live [on PyPI](https://pypi.org/project/awslimitchecker/) and [Docker Hub](https://hub.docker.com/r/jantman/awslimitchecker). Thank you so much, and apologies for the delay!

**Pull request merged**
