### PR TITLE
Implement NAT gateways

### PR DESCRIPTION
**Pull request by hltbra**
This pull request implements a limit check for NAT gateways.

I reviewed the code guidelines, rebuilt the docs after changing it, wrote tests for the new feature, and this PR includes the Contributor License Agreement. Please let me know if anything else is necessary.

---

Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

__IMPORTANT:__ Please take note of the below checklist, especially the first two items.

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, feel free to ask for help or submit the PR without tests.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.
- [x] If you made changes to the ``versioncheck`` code, be sure to locally run the
``-versioncheck`` tox tests.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@hltbra I just finished work for the day, but glancing over it, this looks _wonderful_ and like one of the best PRs I've seen. I'll try to get it reviewed in more detail and hopefully merged tonight. If not, I'll get that done tomorrow.

Thanks so much!
-Jason

**Comment by jantman** [comment]
@hltbra This is __great__ work, thanks so much! I should be able to cut a release in the next few days.

**Comment by hltbra** [comment]
Thanks for the kind words, @jantman.

@spulec and I are using your tool to create a project similar to trusted advisor's service limits (TA is very incomplete). We integrate it with the support API to get past limit increases to make it easy to keep limits up-to-date: https://github.com/spulec/awslimits

It currently works for some things we're doing, but we need to make it more generic and add documentation.

**Comment by jantman** [comment]
Of course, @hltbra ! Most of my personal projects are very small and rarely attract attention, so I'm very happy whenever someone contributes.

Cool, I'll be very interested to see how it turns out. I really don't have the spare time to give it a spin right now, but any chance you have some screenshots or further info?

I'm running into some issues with integration tests since merging this PR. They're not your fault... but the test run (i.e. [this one](https://travis-ci.org/jantman/awslimitchecker/jobs/151196628)) queries VPC a number of times (for usage it looks like 7 times) and 1-2 of them are failing on every run with a ``ClientError: An error occurred (AuthFailure) when calling the DescribeNatGateways operation: This request has been administratively disabled`` error. I'm not sure if it's rate limiting or what, but the IAM policy looks right.

I'll be digging into this later today or tomorrow.

**Comment by jantman** [comment]
@hltbra sorry for the delay; this is now released in 0.5.1 and live on PyPI

**Comment by qwcode** [comment]
this limit is documented in AWS as *per AZ*
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-gateways

but this PR codes it as a global limit.

the logic in `_find_usage_nat_gateways` needs to be updated accordingly, right?

hey @hltbra, been awhile  : )

**Comment by jantman** [comment]
Ugh. Yeah, we completely missed that.

@qwcode @hltbra opened #214 for this; any comments there are appreciated.

**Comment by hltbra** [comment]
Good catch, @qwcode (and yes, long time!).

**Pull request merged**
