### PR TITLE
fixes #273 - add support for new i3 instance types

### LINKED ISSUE #273: Support i3 instances
AWS recently announced a new instance type, i3, a Storage Optimized Instance. Add support for it.

### PR DESCRIPTION
**Pull request by tamsky**
```
# pytest awslimitchecker/tests/services/test_ec2.py
=================================== test session starts ===================================
platform darwin -- Python 2.7.13, pytest-3.1.1, py-1.4.33, pluggy-0.4.0
rootdir: [elided]/src/github/awslimitchecker, inifile: pytest.ini
collected 28 items 

awslimitchecker/tests/services/test_ec2.py ............................

================================ 28 passed in 1.13 seconds ================================
```

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

Signed-Off-By: <tamsky@users.noreply.github.com> Marc Tamsky

### CODE REVIEW

**Comment by tamsky** [comment]
Yes, I sorted the list of instance types in special_limits().

**Comment by jantman** [comment]
@tamsky thanks so much for this! The changes all look good to me, I'm just waiting for Travis to finish the tests. Assuming they're good I'll merge this now, and be targeting a new release in the next 7-8 days or so. I'll try for sooner if I can, but I want to get a few other issues handled in the next release as well.

**Comment by jantman** [comment]
The docs build is failing, but because of a file that wasn't touched in this diff. Merging.

**Comment by jantman** [comment]
This has been released as [0.9.0](https://github.com/jantman/awslimitchecker/releases/tag/0.9.0) and is now [live on PyPI](https://pypi.python.org/pypi/awslimitchecker) ([CHANGELOG](http://awslimitchecker.readthedocs.io/en/0.9.0/changes.html#id1)).

**Pull request merged**
