### PR TITLE
Update DynamoDB and EFS limits #390

### PR DESCRIPTION
**Pull request by bergkampsliew**
# Summary

Update DynamoDB and EFS limits
More info on the issue : https://github.com/jantman/awslimitchecker/issues/390

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@bergkampsliew Thank you so much for the contribution!

A number of these limits appear in the unit tests as well, hence the failed build. If you wouldn't mind updating them, that would be greatly appreciated.

If the unit tests pass, I can get this merged today and should be able to get a release out within the next 24 hours.

**Comment by bergkampsliew** [comment]
yeah, i just noticed the error... committing the fix to the unit test now, thanks

**Comment by jantman** [comment]
Thanks so much! Merging now. I should be able to get a release out tonight, I'll update here and on the issue once it's live on PyPI.

**Comment by jantman** [comment]
This has been released as [6.1.3](https://github.com/jantman/awslimitchecker/releases/tag/6.1.3) via #393 and is now live [on PyPI](https://pypi.org/project/awslimitchecker/).

Thank you so much for the contribution!

**Comment by bergkampsliew** [comment]
that's really fast 🥇  thanks!

**Pull request merged**
