### PR TITLE
Issue #70 - Add ElasticBeanstalk service

### PR DESCRIPTION
**Pull request by bflad**
This PR adds the ElasticBeanstalk service, with three initial limits for checking:
* Applications
* Application versions
* Environments

Passes all Python 2.7 unit tests and verified using my AWS QA environment for Elastic Beanstalk.

```
tox -e py27-unit
...
awslimitchecker/tests/services/test_elasticbeanstalk.py PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_init PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_get_limits PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_get_limits_again PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_find_usage PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_find_usage_applications PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_find_usage_application_versions PASSED
awslimitchecker/tests/services/test_elasticbeanstalk.py::Test_ElasticBeanstalkService::test_find_usage_environments PASSED
...
-------------------------------------------- coverage: platform darwin, python 2.7.10-final-0 ---------------------------------------------
Name                                        Stmts   Miss Branch BrMiss  Cover   Missing
---------------------------------------------------------------------------------------
...
awslimitchecker/services/elasticbeanstalk      38      0      4      0   100%
...
---------------------------------------------------------------------------------------
TOTAL                                        1554      0    476      0   100%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
========================================================= short test summary info =========================================================
SKIP [1] awslimitchecker/tests/test_versioncheck.py:1138: not running py26 test on 2.7.10
SKIP [1] awslimitchecker/tests/test_versioncheck.py:1185: not running py3 test on 2.7.10
SKIP [1] awslimitchecker/tests/services/test_base.py:77: test for py26
SKIP [1] awslimitchecker/tests/services/test_base.py:99: test for py3
SKIP [49] /Users/bflad/Virtualenvs/awslimitchecker-issues-70/src/awslimitchecker/.tox/py27-unit/lib/python2.7/site-packages/pytest_flakes.py:75: file(s) previously passed pyflakes checks
SKIP [1] awslimitchecker/tests/test_versioncheck.py:1112: not running py26 test on 2.7.10
SKIP [1] awslimitchecker/tests/services/test_base.py:88: test for py27

======================================================== slowest 10 test durations ========================================================
0.33s call     awslimitchecker/tests/test_versioncheck.py
0.24s call     awslimitchecker/tests/test_runner.py
0.20s call     awslimitchecker/tests/services/result_fixtures.py
0.16s call     awslimitchecker/tests/test_checker.py
0.14s call     awslimitchecker/tests/test_checker.py::TestAwsLimitChecker::test_init_sts_external_id
0.14s call     awslimitchecker/tests/services/test_ec2.py::Test_Ec2Service::test_find_usage
0.14s call     awslimitchecker/tests/test_limit.py
0.13s call     awslimitchecker/tests/test_connectable.py
0.11s call     awslimitchecker/tests/test_trustedadvisor.py
0.10s call     awslimitchecker/tests/test_runner.py::TestAwsLimitCheckerRunner::test_entry_list_services
===================================== 46 tests deselected by "-m 'not (versioncheck or integration)'" =====================================
========================================== 399 passed, 55 skipped, 46 deselected in 9.57 seconds ==========================================
_________________________________________________________________ summary _________________________________________________________________
  py27-unit: commands succeeded
  congratulations :)

awslimitchecker -S ElasticBeanstalk -l
awslimitchecker 0.4.1@b2127a6* is AGPL-licensed free software; all users have a right to the full source code of this version. See <git@github.com:bflad/awslimitchecker.git>
WARNING:awslimitchecker.trustedadvisor:Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
ElasticBeanstalk/Application versions  500
ElasticBeanstalk/Applications          25
ElasticBeanstalk/Environments          200

awslimitchecker -S ElasticBeanstalk -u
awslimitchecker 0.4.1@b2127a6* is AGPL-licensed free software; all users have a right to the full source code of this version. See <git@github.com:bflad/awslimitchecker.git>
WARNING:awslimitchecker.trustedadvisor:Cannot check TrustedAdvisor: AWS Premium Support Subscription is required to use this service.
ElasticBeanstalk/Application versions  15
ElasticBeanstalk/Applications          9
ElasticBeanstalk/Environments          9
```

### CODE REVIEW

**Comment by jantman** [comment]
@bflad sorry for the test failures... it looks like they're due to an issue in the test code itself ( https://github.com/jantman/awslimitchecker/issues/177 ) that I'll work on.

**Comment by jantman** [comment]
@bflad the code looks good to me. Let me just see about getting the integration tests working (or, properly not running for PRs).

**Comment by jantman** [comment]
@bflad if it's not too much trouble, could you rebase this on develop? I believe I've fixed the integration test problem.

No need to post the test results, Travis will run them.

**Comment by bflad** [comment]
All set! Thanks for fixing that!

**Comment by jantman** [comment]
@bflad thanks so much for fixing that.

Let me pull my foot out of my mouth long enough to say this... this whole PR needs to be based on "develop", not master (i.e. open the PR to merge into develop instead of master). If you want to open a new one based on develop, cool. If not, I can pull down this branch and open a new PR for you.

I feel really bad that the contribution process has been so difficult. I'm happy to close this and open a new one with your code, it's really just a matter of whether the effort to do it yourself is worth it to have a merged PR showing up on your GitHub profile...

I wish this was easier, but sadly GitHub still has no way to do this ( https://github.com/isaacs/github/issues/18 ).

**Comment by bflad** [comment]
Sorry totally missed that when I submitted it. New PR to develop: https://github.com/jantman/awslimitchecker/pull/180

**Comment by jantman** [comment]
Closed in favor of https://github.com/jantman/awslimitchecker/pull/180 which is based against develop

**Pull request closed without merging**
