### PR TITLE
Feature/redshift

### PR DESCRIPTION
**Pull request by nadlerjessie**
This PR adds support for checking Redshift limits, specifically manual snapshots and cluster subnet groups. The default limits are specified by Amazon <a href="http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_redshift">here</a>.

Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

__IMPORTANT:__ Please take note of the below checklist, especially the first two items.

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, feel free to ask for help or submit the PR without tests.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@nadlerjessie Thanks so much for this. I just wanted to give you a heads-up that (1) I just cut a release this past weekend, so I don't think the next is coming out terribly soon, and (2) I'm pretty swamped with work this week, so it might be a few days before I really review this.

Also, it looks like this needs a rebase on develop, but the changes should be pretty minor.

I really, really appreciate contributions, especially when they're as thorough as this looks. I know there are some test failures, but I doubt they're terribly complicated. I'll review this as soon as I can; I'll try to this weekend if not before.

Thanks!

**Comment by nadlerjessie** [comment]
@jantman No worries on any of the timing issues, I appreciate the heads up. I have rebased against the develop branch and fixed the issues with the tests. 

Thanks!

**Comment by jantman** [comment]
Apologies for the delay, but thank you so much for the contribution! I'm merging this to develop now, and expect a release within the next few weeks.

**Comment by jantman** [comment]
This was just released in 0.8.0, which is now live on PyPI. Apologies for the long delay before this release.

**Pull request merged**
