### PR TITLE
adding prometheus output

### PR DESCRIPTION
**Pull request by sstarcher**
This is an example for integrating with prometheus.  Prometheus unlike statsd and others keeps state and integrates better when the objects are group smartly.

### CODE REVIEW

**Comment by jantman** [comment]
@sstarcher The solution here is really a wrapper around awslimitchecker, not integrating Prometheus.

For the purpose of #152, the solution needs work within the awslimitchecker public API, i.e. it needs to be instantiated inside the AwsLimitChecker class.

I'd be happy to merge this as an example script in the ``docs/examples/`` directory, if you can include full test coverage for it and make the http server port configurable. However, incorporation of a metrics solution needs to be something that is inside awslimitchecker itself, and can be enabled and configured via either the existing CLI interface or via arguments to the AwsLimitChecker() class, as described in my [comment on 152](https://github.com/jantman/awslimitchecker/issues/152#issuecomment-277992950).

Keep in mind that AwsLimitChecker is only capable of checking one region at a time. Looking at the example code here, if we could simply run prometheus during each individual run (one region), I do feel that this could fit within the current AwsLimitChecker paradigm. We'd simply need to instantiate the metrics service class before doing anything else (this would start the prometheus server, and do whatever other setup is needed) and then have the metrics service class expose methods like ``before_find_usage()``, ``find_usage_finished(limits)``, etc.

If we're adding metrics support to awslimitchecker, at a minimum, I'd like it to be something that will work with statsd and DataDog. I think that a generic solution with a class that's instantiated before any usage/limits are checked, and then has methods that are called at various points in the process, should suffice for most use cases that I'm aware of.

**Comment by sstarcher** [comment]
Yep just giving an example.  I don't have time to dig into the code and determine the best way to implement it inside of awslimitchecker.

**Comment by sstarcher** [comment]
adding config, moved to examples, linted

**Comment by jantman** [comment]
Updated with develop branch; merging now. Thank you for the contribution!

**Comment by jantman** [comment]
This was just released in 0.8.0, which is now live on PyPI. Apologies for the long delay before this release.

**Pull request merged**
