### PR TITLE
Introducing AWS Lambda Limits and Usage

### PR DESCRIPTION
**Pull request by kilsbo**
# Summary

Adds support for AWS Lambda service, using this AWS API call response (`aws lambda get-account-settings`):

```
{
    "AccountLimit": {
        "CodeSizeUnzipped": 262144000, 
        "UnreservedConcurrentExecutions": 1000, 
        "ConcurrentExecutions": 1000, 
        "CodeSizeZipped": 52428800, 
        "TotalCodeSize": 80530636800
    }, 
    "AccountUsage": {
        "FunctionCount": 12, 
        "TotalCodeSize": 2167198
    }
}
```

# Comments from the implementor

In the code base of awslimitchecker, usages and limits are treated equally. However, this is not true for AWS API in regards of the AWS Lambda service. Therefore, I've been coding it in the Lambda Service class to handle this, returning back different limits and usage metric points depending if you issue the -l or -u parameter upon execution of awslimitchecker. This may or maynot pass PR/code review, and I'm happy to oblige if anything around this is determined in need of a change.

My contribution is being made under the same license as the awslimitchecker project (or any subsequent version of that license if adopted by awslimitchecker).

# Pull Request Checklist

- ✅ All pull requests should be __against the develop branch__, not master.
- ✅ All pull requests must include the Contributor License Agreement (see below).
- ✅ Whether or not your PR includes unit tests:
    - ✅ Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - ✅ Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- ✅ Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - ✅ pep8 compliant with some exceptions (see pytest.ini)
    - ✅ 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - ✅ Complete, correctly-formatted documentation for all classes, functions and methods.
    - ✅ documentation has been rebuilt with ``tox -e docs``
    - ✅ Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - ✅ All modules should have (and use) module-level loggers.
    - ✅ **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - ✅ Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by MAPontes** [comment]
Great stuff. Looking forward to this since I too need it :) 👍

**Comment by MAPontes** [comment]
Hi Jason, hope you are feeling better.
Your comment makes a good point. My idea was to monitor in a daily basis the highest concurrent execution of all lambdas to get a report on daily performance and load. However, after reading your comment [here](https://github.com/jantman/awslimitchecker/issues/363#issuecomment-433617727), makes all sense to do this by monitoring the metric on cloudwatch. This was my main point for this PR.
Thinking on the scope of awslimitchecker, it really is odd to have usages without limits and vice-versa. But maybe this could be added in the future as a reporting functionality. Just an idea :)

**Comment by kilsbo** [comment]
So, should I just hide usages when they don't have a set limit?

**Comment by jantman** [comment]
@kilsbo There's not really a way to "hide" usages.

I've been digging deeper into this today. I feel really bad that this PR has been open so long (and that my open source projects haven't really gotten much attention in far too long), so I'm committed to getting this figured out. Here's where things stand right now:

The awslimitchecker API and CLI both have current support for limits without associated Usage; this is currently in place already if your account doesn't use the resource corresponding with a given limit; i.e. if you have no load balancers, the ``ELB/Active load balancers`` Limit will report a usage of zero, but the ``ELB/Listeners per load balancer`` Limit will report an empty list for Usage, and show ``<unknown>`` in the CLI. So in that respect, we should be fine to add Limits that never report a Usage, since that's a current behavior that users already see via either the CLI or the Python API (a [Limit](https://awslimitchecker.readthedocs.io/en/5.1.0/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit) with an [empty list of usages](https://awslimitchecker.readthedocs.io/en/5.1.0/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_current_usage) / [usage_str of "<unknown>"](https://awslimitchecker.readthedocs.io/en/5.1.0/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_current_usage_str)).

The idea of calculating usage for a Limit that's unlimited, on the other hand, is a bit of a gray area. awslimitchecker itself is in conflict on this... the API docs for [AwsLimit.get_limit()](https://awslimitchecker.readthedocs.io/en/5.1.0/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit.get_limit) say that it can return ``int`` or ``None`` with the latter signifying a limit that is explicitly unlimited. But the docs for the [AwsLimit class constructor](https://awslimitchecker.readthedocs.io/en/5.1.0/awslimitchecker.limit.html#awslimitchecker.limit.AwsLimit) specify an ``int`` for ``default_limit``. I'd need to dig quite a bit through the rest of the code to tell if None is even supported internally, let alone would be supported by third-party use cases.

One other note is that for awslimitchecker to work right with the Python API and third-party integrations, you can't define any new Limits in ``find_usage()`` - _all_ limits must be returned by ``get_limits()``.

I'm going to cut my own branch off of this and start working on it a bit and see what I can come up with.

**Comment by jantman** [comment]
Just to follow up on my previous comment re: "unlimited" limits, it appears that as of #197 which was merged over two years ago in [0.5.0](https://github.com/jantman/awslimitchecker/blob/master/CHANGES.rst#050-2016-07-06), we _do_ have support for "unlimited" limits, as Trusted Advisor returns them.

So this should have just gotten a _lot_ simpler, and there's just a documentation issue.

**Comment by kilsbo** [comment]
Thank you for this, much appreciated!

**Pull request merged**
