### PR TITLE
Add Network interfaces per Region limit

### PR DESCRIPTION
**Pull request by nadlerjessie**
# Summary
This PR adds the `Network interfaces per Region` limit. This limit is described [here](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html) is a bit unusual because the default is:
>This limit is the greater of either the default limit (350) or your On-Demand Instance limit multiplied by 5. 

I used 350 because that is the initial limit a new account will have, given that the default limit for On-Demand Instances is 20.

I had some trouble getting the docs to build so I did not complete that step (it is the only failure in travis). Sorry about that!

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [ ] Whether or not your PR includes unit tests:
    - [x] Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - [ ] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
Thanks so much! And thanks for adding the tests as well!

No worries about the docs build, they're rebuilt as part of the release process anyway.

I have a pretty busy week this week, so I might not be able to get this reviewed, merged, and released until the weekend, but I'll do my best.

@nadlerjessie Just a thought regarding the weird "greater of either the default limit (350) or your On-Demand Instance limit multiplied by 5." calculation for this limit... the [DescribeAccountAttributes](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeAccountAttributes.html) EC2 API call returns, among other things, the account's current Running On-Demand EC2 Instances limit in the current region. awslimitchecker is already using that to dynamically update the Running On-Demand EC2 limit [in _Ec2Service._update_limits_from_api()](https://github.com/jantman/awslimitchecker/blob/d8eccf162b9d25690b58cb4b94d31c3d6acaa997/awslimitchecker/services/ec2.py#L294-L295).

Would you have anything wrong with me (or you, if you want) adding some logic to that ``_update_limits_from_api()`` method to update this new Network Interfaces limit, based on the formula and the On-Demand Instance limit data?

**Comment by nadlerjessie** [comment]
I like that idea, I didn't know about `_update_limits_from_api`! I'll take care of it. And no rush on the release, thanks for letting me know.

**Comment by jantman** [comment]
The only build failure was a broken link found by the docs build. Merging now; I'll clean that up before release

**Comment by nadlerjessie** [comment]
You're welcome @jantman! Thanks for maintaining such a great library and for the quick review

**Comment by jantman** [comment]
This has been released as 6.1.0 and is live on PyPI. Thanks again!

**Pull request merged**
