### PR TITLE
Handle AccessDenied exception in SES check #375

### PR DESCRIPTION
**Pull request by bergkampsliew**
# Summary

Handle AccessDenied exception in SES check for non-supported region
More info on the issue : https://github.com/jantman/awslimitchecker/issues/375

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@bergkampsliew I commented on #375 ...

Thank you for the contribution. In order to write tests for this I need a copy of the exact traceback that's being thrown along with the error message, or a region that I can try and reproduce the problem in.

**Comment by bergkampsliew** [comment]
the stacktrace as below, and it's reproducible against region eu-central-1 (you can compare the result from ap-northeast-1 as both regions do not support SES yet)

Traceback (most recent call last):
  File "/usr/local/bin/awslimitchecker", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 415, in console_entry_point
    r.console_entry_point()
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 409, in console_entry_point
    res = self.check_thresholds()
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/runner.py", line 310, in check_thresholds
    service=self.service_name)
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/checker.py", line 553, in check_thresholds
    cls._update_limits_from_api()
  File "/usr/local/lib/python2.7/dist-packages/awslimitchecker/services/ses.py", line 105, in _update_limits_from_api
    resp = self.conn.get_send_quota()
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetSendQuota operation: Unknown

**Comment by jantman** [comment]
Ok, thanks! I'm actually going to be really busy the next few days, but I'll try to get this merged this weekend.

**Comment by jantman** [comment]
This has been released in [6.0.1](https://github.com/jantman/awslimitchecker/releases/tag/6.0.1) which is now live [on PyPI](https://pypi.org/project/awslimitchecker/). Thank you so much @bergkampsliew !!

**Pull request merged**
