### PR TITLE
Add support to Kinesis Firehose delivery streams metric

### PR DESCRIPTION
**Pull request by hltbra**
This pull request creates the service Firehose and implements the metric "'Delivery streams per region".

More information on this limit:
- http://docs.aws.amazon.com/firehose/latest/dev/limits.html
- http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits-akf

---

Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

**IMPORTANT:** Please take note of the below checklist, especially the first two items.
# Pull Request Checklist
- [x] All pull requests should be **against the develop branch**, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
  - [x] pep8 compliant with some exceptions (see pytest.ini)
  - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
    writing tests for the code, feel free to ask for help or submit the PR without tests.
  - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
  - [x] documentation has been rebuilt with `tox -e docs`
  - [x] Connections to the AWS services should only be made by the class's
    `connect()` and `connect_resource()` methods, inherited from
    [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
  - [x] All modules should have (and use) module-level loggers.
  - [x] **Commit messages** should be meaningful, and reference the Issue number
    if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
    refrain from using the "fixes #x" notation unless you are _sure_ that the
    the issue is fixed in that commit.
  - [x] Git history is fully intact; please do not squash or rewrite history.
- [x] If you made changes to the `versioncheck` code, be sure to locally run the
  `-versioncheck` tox tests.
## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:
- The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
- My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
- I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
@hltbra I'm so sorry for letting this sit so long. awslimitchecker is purely a personal time project for me, and I haven't had much time to commit to it lately.

This looks great to me! Would you mind rebasing on ``develop``, and then I'll pull this in for the next release (which should be coming this weekend)?

Thanks!
Jason

**Comment by jantman** [comment]
Used the "Update branch" button, waiting for tests...

**Comment by jantman** [comment]
Merging. Thanks so much!

Anticipating a release this weekend.

**Comment by hltbra** [comment]
No problem, @jantman. Thanks for merging these changes!

**Comment by jantman** [comment]
This has been released in 0.6.0 and is now live on PyPI

**Pull request merged**
