### PR TITLE
Fix sts credentials reusage

### PR DESCRIPTION
**Pull request by dsumsky**
STS credentials for one AWS account seem to be reused when connecting to another AWS account before they expire. The issue is reported as #221.

I want to write a function to check limits/thresholds in multiple AWS accounts at once.  The code below returns number of S3 buckets in  ACCOUNT01 account correctly but it is incorrect for  ACCOUNT02 account as the STS credentials from ACCOUNT01 account are reused.

Testing code to reproduce the issue:
```
#!/usr/bin/env python
from awslimitchecker.checker import AwsLimitChecker

def foo(event):
    # input parameters for checker
    service = event['service']
    region = event['region']
    account_name = event['account_name']
    account_id = str(event['accounts'][account_name]['id'])
    account_role = event['account_role']

    checker = AwsLimitChecker(account_id=account_id, 
                              account_role=account_role, region=region)
    checker.check_thresholds(service)
    result = checker.get_limits(service)[service]

    for limit_name, limit in result.items():
        limitstr = str(limit.get_limit())
        usagestr = str(limit.get_current_usage_str())

        print("Service usage: account_name: {}, region: {}, service: {}, \
              limit_name: {}, limit: {}, limit_usage: {}".format(account_name, \
              region, service, limit_name, limitstr, usagestr))


if __name__ == "__main__":
    event = {
        u'service': 'S3',
        u'region': 'us-east-1',
        u'account_name': 'ACCOUNT01',
        u'account_role': 'ALC_ROLE',
        u'accounts': {
            u'ACCOUNT01': {
                u'id': XXXXXXXXXXX01
            },
            u'ACCOUNT02': {
                u'id': XXXXXXXXXXX02
            }

        }
    }

    foo(event)

    event['account_name'] = 'ACCOUNT02'

    foo(event)
```
## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
At first glance this looks good to me. I'm swamped today, but should be able to look deeper at this tonight or tomorrow, and I can make the test additions/fixes for it.

Have you used this code yourself, and can you confirm that it's working and fixes the issue?

**Comment by dsumsky** [comment]
I tested it today and it works fine with pure STS/AssumeRole but  without MFA token. I'm just not  sure if it does not interfere with MFA related code.

**Comment by jantman** [comment]
@dsumsky sorry for the delay on this.

I should be able to fix the tests, but this needs to be rebased on develop. If it's OK with you, I'll pull this PR into a branch of mine, rebase it, fix the tests, and open a new PR from that. You'll still be tracked as the contributor as far as the commits are concerned...

**Comment by jantman** [comment]
Oh wow... there's now an "Update branch" button where, apparently, I can rebase your branch on the target... weird... but cool.

**Comment by dsumsky** [comment]
it's definitely ok, do what you need to do.

Dne 10. 11. 2016 10:50 odpoledne napsal uživatel "Jason Antman" <
notifications@github.com>:

**Comment by jantman** [comment]
I'm closing this in favor of #225 which has my fixes in it. Thanks so much for this!!!!

**Comment by jantman** [comment]
This has been released in 0.6.0 and is now live on PyPI

**Pull request closed without merging**
