### PR TITLE
add support for Prometheus AlertManager

### PR DESCRIPTION
**Pull request by varuzam**
# Summary
 support for Prometheus AlertManager #474 
```
awslimitchecker \
    --alert-provider=AlertManager \
    --alert-config=endpoints=http://alertmanager1:9093,http://alertmanger2:9093 \
    --alert-config=basic_auth_username=user \
    --alert-config=basic_auth_password=pass \
    --alert-config=alert_duration=1800
```
## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jantman** [comment]
Thank you so much for your contribution, and please accept my apologies for not responding sooner. I've been quite busy lately and unable to dedicate any time to my open source projects. I'm going to make every effort to review this and get it merged sometime this week.

**Comment by jantman** [comment]
I'm really embarrassed to say this, but I honestly don't remember what the state of this PR is. Was there any further discussion on this, or is it still just waiting on review and merge from me, and addition of unit tests?

**Comment by jantman** [comment]
@varuzam Are you still interested in having this merged, or have you moved on?

If I don't get a response within a week, I'm likely going to close this PR as stale.

**Comment by varuzam** [comment]
unnecessary commits got into the PR. I can create a new one.

**Pull request closed without merging**
