### PR TITLE
Fix calculation of VPC Network Interfaces limit

### PR DESCRIPTION
**Pull request by TimGebert**
# Summary

Fixes calculation for VPC Network Interface limit.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by bergkampsliew** [comment]
looks like unit test needs fixing

**Comment by jantman** [comment]
Tim,

Thanks for the contribution! I wasn't aware of that bug in the NI limit calculation, and nobody else has noticed this yet either! It appears this was introduced in #379 and released in 6.1.0 about a month ago.

I'm going to be rather busy the next few days, so I _might_ be able to get this fixed up and released while I'm working on other things, or else it might not be released until the weekend or early next week.

Yes, the unit test is definitely causing a build failure, because they're testing the previous logic. It should only take 3 changes to fix them. The [unit test in question](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/tests/services/test_vpc.py#L364-L386) has a [sample API response](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/tests/services/result_fixtures.py#L632) with "400" as the max-instances limit returned by the EC2 API, and [expects](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/tests/services/test_vpc.py#L385-L386) the Network interfaces per Region limit to also be 400. Since it appears that the limit should really be multiplied by five but that was never done in the code, we'll want to expect the resulting Network interfaces per Region limit to be 2000 instead of 400... so the unit tests should be fixed by just changing the ``400`` on [lines 385 and 386 of tests/services/test_vpc.py](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/tests/services/test_vpc.py#L385-L386) to ``2000``.

Thanks,
Jason

PS - Tim, this bug happened to be pretty obvious when looking at the changes in this PR. In the future, though, it would be helpful if you provided a more detailed overview of the problem for PRs that don't already have a matching issue containing all of the details requested in the [issue template](https://github.com/jantman/awslimitchecker/blob/master/.github/ISSUE_TEMPLATE.md).

( cc @nadlerjessie on this PR, as I assume her employer is also using this code )

**Comment by jantman** [comment]
I'm going to merge this now and try to get a release out today. I'll update when it's live on PyPI.

Thanks so much for the contribution, @TimGebert !!

**Comment by jantman** [comment]
This has been released as [6.1.4](https://github.com/jantman/awslimitchecker/releases/tag/6.1.4) and is live [on PyPI](https://pypi.org/project/awslimitchecker/).

Thank you so much!

**Comment by TimGebert** [comment]
Thanks @jantman for making it easy to get this in so easily, and constantly supporting the repo :)

**Pull request merged**
