### PR TITLE
Handle govcloud-specific edge cases.

### PR DESCRIPTION
**Pull request by jmcarp**
Handle govcloud-specific edge cases.

* Handle errors on spot instance and fleet requests
* Handle false zero limit on EIP

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by jmcarp** [comment]
@jantman: if this looks all right to you, I'll backfill tests. Let me know!

**Comment by jantman** [comment]
@jmcarp Aplogies for this sitting for so long, I've had some family stuff going on that limited my time spent on personal projects.

Looks great to me. If you can backfill the tests, I'll get this in the next release.

PS - Hey, you're one of those 18F people! You rock!

**Comment by jantman** [comment]
Thanks so much for this!

**Comment by jantman** [comment]
This was just released in 0.8.0, which is now live on PyPI. Apologies for the long delay before this release.

**Pull request merged**
