### PR TITLE
s3: Only find buckets in our region

### PR DESCRIPTION
**Pull request by iainlane**
Quotas for S3 buckets are regional. Currently though, we are returning buckets in all regions when we query the API. This means that we sum all buckets in all regions against the quota for each region (modulo issue #513), i.e. we over-report usage.

We can fix this by doing a `head_bucket` call for each bucket, and only counting the ones that are in our current region.

Note that this needs the `s3:ListBucket` IAM permission.

Before submitting pull requests, please see the
[Development documentation](http://awslimitchecker.readthedocs.org/en/latest/development.html)
and specifically the [Pull Request Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#pull-requests).

__IMPORTANT:__ Please take note of the below checklist, especially the first three items.

# Summary

*Add a summary of what your PR does here. This could be as simple as "adds support for X service" or "fixes default limit for Y", or a longer explanation for less straightforward changes.*

# Pull Request Checklist

- [x] All pull requests should be __against the develop branch__, not master.
- [x] All pull requests must include the Contributor License Agreement (see below).
- [x] Whether or not your PR includes unit tests:
    - [x] Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - [ ] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [x] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [x] pep8 compliant with some exceptions (see pytest.ini)
    - [x] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [x] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [x] documentation has been rebuilt with ``tox -e docs``
    - [x] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [x] All modules should have (and use) module-level loggers.
    - [x] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [x] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by iainlane** [comment]
Looks like Travis isn't going to start running so I will un-draft anyway.

**Comment by jwu2** [comment]
Where did you get `Quotas for S3 buckets are regional`? It appears that the quota is global per account per:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html

**Comment by iainlane** [comment]
I think I read [this page](https://docs.aws.amazon.com/general/latest/gr/s3.html) before making the PR. It says:

> Buckets | Each supported Region: 100 [...] The number of Amazon S3 buckets that you can create in an account

Reading that again in the light of your comment I'm not actually 100% clear either way - why does it say "Each supported region"? - but the page you linked _is_ quite clear. Hmm.

I'll dig a bit more, stand by.

**Comment by iainlane** [comment]
I contacted AWS support and they confirmed it is account-wide. I suggested they update the docs to be more definitive. Thanks for the poke, will close this PR.

**Pull request closed without merging**
