### PR TITLE
issue #488 - Update ElasticCache default limits

### PR DESCRIPTION
**Pull request by sebasrp**
# Summary

issue #488 - Update the following ElasticCache default limits: Nodes, Nodes per Cluster, Subnet Groups, Parameter Groups

# Pull Request Checklist

- [X] All pull requests should be __against the develop branch__, not master.
- [X] All pull requests must include the Contributor License Agreement (see below).
- [X] Whether or not your PR includes unit tests:
    - [X] Please make sure you have run the exact code contained in the PR locally, and it functions as desired.
    - [X] Please make sure the TravisCI build passes or, if not, you've corrected any obvious problems identified by the tests.
- [X] Code should conform to the [Development Guidelines](http://awslimitchecker.readthedocs.org/en/latest/development.html#guidelines):
    - [X] pep8 compliant with some exceptions (see pytest.ini)
    - [X] 100% test coverage with pytest (with valid tests). If you have difficulty
      writing tests for the code, that's fine, just mention that in the summary and either
      ask for assistance, or clarify that you'd like someone else to handle the tests. PRs that
      include complete test coverage will usually be merged faster.
    - [X] Complete, correctly-formatted documentation for all classes, functions and methods.
    - [X] documentation has been rebuilt with ``tox -e docs``
    - [X] Connections to the AWS services should only be made by the class's
      ``connect()`` and ``connect_resource()`` methods, inherited from
      [awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimitchecker.connectable.html)
    - [X] All modules should have (and use) module-level loggers.
    - [X] **Commit messages** should be meaningful, and reference the Issue number
      if you're working on a GitHub issue (i.e. "issue #x - <message>"). Please
      refrain from using the "fixes #x" notation unless you are *sure* that the
      the issue is fixed in that commit.
    - [X] Git history is fully intact; please do not squash or rewrite history.

## Contributor License Agreement

By submitting this work for inclusion in awslimitchecker, I agree to the following terms:

* The contribution included in this request (and any subsequent revisions or versions of it)
  is being made under the same license as the awslimitchecker project (the Affero GPL v3,
  or any subsequent version of that license if adopted by awslimitchecker).
* My contribution may perpetually be included in and distributed with awslimitchecker; submitting
  this pull request grants a perpetual, global, unlimited license for it to be used and distributed
  under the terms of awslimitchecker's license.
* I have the legal power and rights to agree to these terms.

### CODE REVIEW

**Comment by sebasrp** [comment]
one of the things I've been unable to do is generate the updated documentation (to update https://github.com/jantman/awslimitchecker/blob/master/docs/source/limits.rst for example) - the command ``tox -e docs``` does not seem to catch the new defaults

**Comment by jantman** [comment]
@sebasrp It looks as though something may have changed again since this PR was merged. Looking at https://docs.aws.amazon.com/general/latest/gr/elasticache-service.html today I now see a "Nodes per cluster (Memcached)" limit with a default that's back down to 20, and a "Nodes per cluster  per instance type (Redis cluster mode enabled)" limit with a default of 90. The current awslimitchecker code only appears to check Memcache clusters for "Nodes per Cluster".

**Comment by sebasrp** [comment]
I am trying to figure out the latest info on the documentation is correct or not.
Seems like the quotas are no longer on the service quota console page (not sure why?) - so im going to investigate this week to figure out the latest from the service quota api and update this PR

**Comment by jantman** [comment]
Ok, thanks so much! I'm planning the 10.0.0 release on Monday December 7th.

**Comment by sebasrp** [comment]
It seems elasticache is not onboarded in aws service quotas, so the information we have is purely from the documentation. I will update the PR to match the documentation and also reach out to one of the TAMs to confirm in parallel

**Comment by jantman** [comment]
> It seems elasticache is not onboarded in aws service quotas, so the information we have is purely from the documentation. I will update the PR to match the documentation and also reach out to one of the TAMs to confirm in parallel

Ok, thanks so much! If you're reaching out to your TAMs, I'll hold off on opening a ticket on one of our accounts. For what it's worth, the ElastiCache docs are on github ( https://github.com/awsdocs/amazon-elasticache-docs )... but, very unfortunately, the service limits docs have been moved from the individual service docs to the General Reference (e.g. https://docs.aws.amazon.com/general/latest/gr/elasticache-service.html ) and that doc is _not_ on github... so we no longer have commit history to see when the limit docs changed.

**Comment by sebasrp** [comment]
I've updated the PR to revert to 20 nodes per cluster (memcached).

**Review by jantman — APPROVED** [review]

**Pull request merged**
